wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684520346.170848
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 19
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 1
      - 3
      - 5
embed_size:
  desc: null
  value: 400
hidden_size:
  desc: null
  value: 512
vocab_size_train:
  desc: null
  value: 3293
num_layers:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.0003
device:
  desc: null
  value: cuda
scheduler:
  desc: null
  value: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x000001F4920E9180>
