wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1684521638.018267
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.2
      8:
      - 1
      - 3
      - 5
